# Generated by Django 4.1.2 on 2023-02-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_plan_category_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['create_date']},
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='create_deate',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='progress',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.plan'),
        ),
    ]
